name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - colour-science
    - seaborn
    - imageio
    - ipywidgets
    - latex
    - tex
    - PyLaTeX
    - texlive-core

